### ISSUE TITLE
Lilu 1.2.0/1.2.1 and plugin incompatibility (AppleALC 1.2.0/1.2.1, NvidiaGraphicsFixup 1.2.0/1.2.1) with Skylake-X/X299 System

### ISSUE THREAD

**Issue by KGP** [vit9696/Lilu#30] opened 2017-11-04 10:50 UTC
No way to run Lilu.kext v1.2.0 or v1.2.1 and related plugins like e.g. AppleALC.kext v1.2.0 or v1.2.1 and NvidiaGraphicsFixup.kext v1.2.0 or v1.2.1 on my Skylake-X/X299 System -> KP towards the end of the boot process resulting in a boot loop like behaviour... 

Also the KernelToPatch entry 8A 02 84 C0 74 44 → 8A 02 84 C0 EB 44 in the "Kernel and Kext Patches" Section of Clover Configurator does not help at all! 

I still have to work with Lilu.kext v1.1.7, AppleALC.kext v1.1.4 and NvidiaGraphicsFixup.kext v1.1.3, which work fine... 

No problems though with Lilu.kext v1.2.0 or v1.2.1 and related plugins like e.g. AppleALC.kext v1.2.0 or v1.2.1 and NvidiaGraphicsFixup.kext v1.2.0 or v1.2.1 on my Broadwell-E/X99 System.

**Comment by vit9696** [comment] 2017-11-04 14:07
Works for me, not reproducible. Come back once you learn how to bugreport.

**Comment by KGP** [comment] 2017-11-04 14:30
Thanks for your stupid and impolite answer! :-( :-( :-( How to bug report  a KP??? In 1 second 100 lines pass the screen... it is impossible to follow what exactly happens due to your kexts...

**Comment by vit9696** [comment] 2017-11-04 14:47
Well, if you are incapable to see the mistakes you left, let me point them out, since they are way too common across all the users here coming with an assumption it is a 24/7 helpdesk.

1. You did not post anything about your OS, be it 10.12, 10.13, which build (e.g. 16G1036)
2. You did not post about the actual version of 1.2.1 you tried. Until 1.2.1 is released you could only operate by commit hashes obviously, since the changes are made all the way (e.g. 0d7b8a8). Furthermore, you said nothing about DEBUG/RELEASE builds used. Even more, if you submit a report for a prerelease version, you should attach a binary (otherwise it is hardly possible to get to an exact place).
3. You did not post anything about your boot arguments and did not care to read how to specify them (otherwise you would not have said any nonsense about "100 lines pass the screen", it is very easy to clearly get a panic image with a call trace by specifying `debug=0x100 keepsyms=1` and if you are on 10.13 you also need the patch you mentioned above).
4. There also are many other issues like macmodel, where you installed your kexts to, which combinations of kexts work and which do not (e.g. Lilu alone works but installing AppleALC immediately leads to a KP), and so on…

What you posted above is nothing but an informal support request, and it is not a bugreport. Please understand that on a bug tracker people are supposed to report _bugs_. And bug reporting is usually not something that could be done casually, there is a dedicated profession for such stuff if you did not know.

If you cannot write bugreports, you should go to the forums, because I obviously cannot spend days on explaining all the same things to the users.

**Comment by KGP** [comment] 2017-11-04 15:09
I have a ASUS Prime X299 Deluxe, i9-7980XE and a Gigabyte Aorus GTX 1080 Ti Waterfoce WB Extreme Edition. 

My SMBIOS is iMac 17,1,.  The Lilu.kext issues are related to both macOS High 10.13 SU and 10.13.1.

Using your officially distributed Lilu.kext v1.2.0 release either in combination with your officially distributed NvidiagraphicsFixup 1.2.0 or 1.2.1 release, or with the officially distributed AppleALC.kext v1.2.0 release (everything directly downloaded from github as precompiled kexts), or obviously also by using the combination off all three kexts together, I just notice a KP during boot ... I use the kexts in /EFI/CLOVER/kexts/Other/. I don't use any boot arguments apart from -v, darkwake=0, slide=1, dart=1, and ncpi=0x2000... 

In contrary, everything works fine with  Lilu.kext v1.1.7, AppleALC.kext v1.1.4 and NvidiaGraphicsFixup.kext v1.1.3... Same system configuration...

**Comment by KGP** [comment] 2017-11-04 19:47
Ok.. I crashed my rig two times more to finally and hopefully get your response and support. 

Please see the detailed results, description and report above. 

I hope that now the information suffice to finally get and draw your attention.

**Comment by vit9696** [comment] 2017-11-04 19:50
Right, finally we have something sane and clear here. I am pretty sure this is fixed in the latest development version (0d7b8a8). Please clone the latest source from the repository and compile it yourself. Just updating Lilu will be enough.

**Comment by KGP** [comment] 2017-11-04 19:56
To clarify, I should download the source for Lilu.kext 1.2.1 and compile it myself? I guess I than also need to download the source for AppleALC.kext 1.2.1 and NvidiagraphicsFixup 1.2.1? Or can I just use Lilu.kext 1.2.1 with AppleALC.kext 1.2.0 and NvidiagraphicsFixup 1.2.0?

Thanks for clarifaction..

**Comment by vit9696** [comment] 2017-11-04 19:57
> To clarify, I should download the source for Lilu.kext 1.2.1 and compile it myself? I

Correct. You may update/recompile the other kexts as well, but there is no particular need in it in your case.

**Comment by KGP** [comment] 2017-11-04 20:29
O.k. just downloaded and successfully compiled the Lilu.kext source v1.2.1 from the Repository.

Now with Lilu.kext v1.2.1 +  NvidiagraphicsFixup v1.2.0 + AppleALC.kext v1.2.0 in /EFI/CLOVER/kexts/Other/ and the KernelToPatch entry 8A 02 84 C0 74 44 → 8A 02 84 C0 EB 44, the KP issue has apparently reduced to Lilu.kext v1.2.1 + AppleALC.kext 1.2.0 However, as you see in the picture below, I still witness a KP, obviously caused by the latter two kext-files. 

![kp-lilu1 2 1 nvidiagraphicsfixup1 2 0 applealc1 2 0](https://user-images.githubusercontent.com/8530784/32409152-8e6c9d8e-c1a6-11e7-8f8f-9f6e2a9a45b5.JPG)

What to do next?

Separate question: is there any guideline to properly compile the source for AppleALC and NvidiagraphicsFixup? My intents to just compile the downloaded source failed in both cases. What am I missing here or what do I have to consider in addition?   

Thanks in advance for your response and help!

**Comment by vit9696** [comment] 2017-11-04 20:33
That sounds bad. The issue is related to a corrupted kext cache, but for some unobvious reason Lilu still fails to detect it. Could you try adding `-lilulowmem` boot argument and try loading?

As for compiling the other plugins it is all about copying Lilu.kext to their directories. This is unrelated to the problem.

**Comment by KGP** [comment] 2017-11-04 21:02
Success! 

Now with boot flag -lilulowmem, with lilu.kext 1.2.1, NvidiagraphicsFixup.kext 1.2.1 and AppleALC.kext v1.2.0 in /EFI/CLOVER/kexts/Other/ and including the 8A 02 84 C0 74 44 → 8A 02 84 C0 EB 44 KernelToPatch entry, the system finally boots successfully. Graphics 100% success. Audio 100% success. 

Many thanks for now! Don't know if you would be able to further improve Lilu thus finally would be able to skip both additional boot flag and Kernel Patch.  

Independent question: I copied now the newly compiled Lilu.kext v1.2.1 to the "AppleALC-master" and "NvidiaGraphicsFixup-Source" directories. 

However it seems that my Lilu.kext misses the Resource directory, in Contents...

I still get the following Xcode 9.1 compilation errors:

NvididaGraphicsFixup:

`error: no such file or directory: '/Users/kgp/Desktop/NvidiaGraphicsFixup-1.2.1-Source/Lilu.kext/Contents/Resources/Library/plugin_start.cpp'
clang: error: no input files

** BUILD FAILED **

The following build commands failed:
	CompileC build/NvidiaGraphicsFixup.build/Release/NvidiaGraphicsFixup.build/Objects-normal/x86_64/plugin_start.o Lilu.kext/Contents/Resources/Library/plugin_start.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
`
AppleALC: 

`** BUILD FAILED **


The following build commands failed:
	CompileC build/AppleALC.build/Release/AppleALC.build/Objects-normal/x86_64/plugin_start.o Lilu.kext/Contents/Resources/Library/plugin_start.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)`

**Comment by vit9696** [comment] 2017-11-04 21:10
The fact that it works does not change the fact that your system has borked kextcache. If you remove this argument and reboot does it panic reproducibly? Also, what do you see if you run the following command in Terminal:
```
ioreg -l | grep OSPrelinkKextCount
```

As for your other question: To build plugins you need to compile a DEBUG Lilu.kext.

**Comment by vit9696** [comment] 2017-11-04 21:19
Also, why do you need `slide=1`? The value is hardly valid I should say (normally KASLR is random and is aligned to 20 bits). Does anything change if you remove this boot argument?

**Comment by KGP** [comment] 2017-11-04 21:31
```
ioreg -l | grep OSPrelinkKextCount  | "OSPrelinkKextCount" = 297
```

I don't want to further crash my system with further tests. Can I fix the borked kextcache of my system? 

Yes, I can easily remove ```slide=1``` without any issue or further effect on my system. In fact I included the latter boot flag on user request. I already forgot the exact reason, but if I properly remember it was related with some graphics glitches he supposedly observed without the boot flag.

**Comment by vit9696** [comment] 2017-11-04 21:35
Thanks. Check `kextcache` utility manual to rebuild kext cache, this should solve the issues in normal case.
I suspect that `slide=1` could be the cause of the kextcache issues, but I do not have enough evidence. In my view it is better not to use it unless you really need to, and even if you do, the value should probably be saner.

**Closed by vit9696** 2017-11-04 21:35 UTC

**Comment by KGP** [comment] 2017-11-04 22:00
o.k. I just rebuild my kext cache

```
sudo touch /Library/Extensions && sudo kextcache -u /

sudo touch /System/Library/Extensions && sudo kextcache -u /
```

and also removed boot flag ```-lilulowmem```

System now boots perfectly with the ```-lilulowmem``` boot flag!

Gorgeous!  

Do you think I still need KernelToPatch entry?

**Comment by vit9696** [comment] 2017-11-04 22:01
The entry is only necessary to disable extra output from the kernel when the system panics. It is not needed for anything but debugging.

**Comment by tengg** [comment] 2017-11-06 04:31
Odd. I had the same panic with 1.20/1.21.
Used -lilulowmem, boot successfully.
But I used @KGP kernel cache redo command, still panic/reboot without lilulowmem.

**Comment by KGP** [comment] 2017-11-06 07:54
Yes it is weird... After rebuilding the kernelchache, I was able to boot once successfully without 
```-lilulowmem```. When booting the next time, the KP due to AppleALC.kext was back. 

I don't know what apparently and repeatedly causes the bork of my kextkache. I also removed now boot flags ```slide=0``` and ```dart=0```, thus I am left with boot flags ```-v``` and ```ncpi=0x2000``` as well as ```debug=100``` and ```keepsyms=1```. 

However, no way to boot without the ```lilulowmem``` bootflag

I might mention, that I use in addition three ACPI drop tables:

```
DMAR
SSDT      Tabled      Cpu0lst
SSDT      Tabled      Cpu0Pm
``` 
 as well as ```Pugin Type 1``` and ```PLimit Dict 0```.

In EFI/CLOVER/kexts/Other/ I still use ```FakeSMC.kext v6.25-333-g05e0f4be.1759```, ```IntelMausiEthernet.kext v2.3.0``` ```SmallTree-Intel-211VA-PCIe-GBE.kext v1.0``` and ```VoodooTSCSync.kext```...

Furthermore at midnight I downloaded  the most actual sources for lilu.kext v1.2.1, AppleALC v1.2.1 and NvidiagraphicsFixup v1.2.1 and successfully compiled all three kexts with Xcode 9.1.

[Lilu.kext.zip](https://github.com/vit9696/Lilu/files/1445357/Lilu.kext.zip)

[NvidiaGraphicsFixup.kext.zip](https://github.com/vit9696/Lilu/files/1445353/NvidiaGraphicsFixup.kext.zip)

[AppleALC.kext.zip](https://github.com/vit9696/Lilu/files/1445349/AppleALC.kext.zip)

I even tried to install all 3 kexts in /L/E/ instead of /EFI/CLOVER/kexts/Other/ including a modified and adopted version of LiluFriend v1.0.

[LiluFriend.kext.zip](https://github.com/vit9696/Lilu/files/1445340/LiluFriend.kext.zip)

On kextcache rebuild, I now get the following notification:

```
 Kext with invalid signatured (-67062) allowed: <OSKext 0x7fdde39b4bc0 [0x7fff87cb4570]> { URL = "LiluFriend.kext/ -- file:///Library/Extensions/", ID = "com.apple.security.LiluFriend" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fdde3922600 [0x7fff87cb4570]> { URL = "Lilu.kext/ -- file:///Library/Extensions/", ID = "as.vit9696.Lilu" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fdde39affe0 [0x7fff87cb4570]> { URL = "NvidiaGraphicsFixup.kext/ -- file:///Library/Extensions/", ID = "as.lvs1974.NvidiaGraphicsFixup" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fdde3931dc0 [0x7fff87cb4570]> { URL = "AppleALC.kext/ -- file:///Library/Extensions/", ID = "as.vit9696.AppleALC" }
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fdde3931f90 [0x7fff87cb4570]> { URL = "PinConfigs.kext/ -- file:///Library/Extensions/AppleALC.kext/Contents/PlugIns/", ID = "as.vit9696.PinConfigs" }
KernelCache ID: 595C2BC1EA4ECA8A92C39A0D6DE312E8
```

However, what ever I do, I now always face again the KP due to AppleALC without the ```-lilulowmem``` boot flag..

**Comment by vit9696** [comment] 2017-11-06 09:17
Well, I kind of gave up trying to understand what is broken for you and several people. I simply reverted some of the code in https://github.com/vit9696/Lilu/commit/b6bbe0f997c484a4c24b292ba610b71979e997b5, and now Lilu should behave similarly to 1.1.x.

**Comment by KGP** [comment] 2017-11-06 09:42
Yes, now I can successfully boot my system with Lilu.kext v1.2.1, AppleALC v1.2.1 and NvidiagraphicsFixup v1.2.1 (sources just downloaded and compiled a few minutes ago with Xcode 9.1 under 10.13.1) without further issues or KP.
