### ISSUE TITLE
lilu.kext kernel panic

### ISSUE THREAD

**Issue by fixpol** [vit9696/Lilu#9] opened 2017-06-08 05:51 UTC
I have constant Kernel Panic trying to fix HD530 with lilu.kext. and IntelGraphixsFixup.kext.
My hardware is asrock mini itx h170m, core -i3 6100. My issues are described in this threadhttps://www.tonymacx86.com/threads/solved-update-10-12-5-initialize-graphic-firmware-failed.222582/page-3 . So may be it will be helpful in next release of lilu.kext

**Comment by vit9696** [comment] 2017-06-08 08:36
Hello, withouts keepsyms=1 in boot-args the panic log is not very helpful. Could you copy the debug versions of the plugins add keepsyms=1 to the boot-args and repeat?

I think you do not have a problem with the Lilu code though, at least it is not even mentioned in the backtrace, so closing the issue.

Also, since you are using Lilu from /L/E, consider building a custom https://github.com/PMheart/LiluFriend plugin.

**Closed by vit9696** 2017-06-08 08:36 UTC

**Comment by fixpol** [comment] 2017-06-08 10:26
Hi,

Please find attached  kp report with keepsyms=1 in boot-args. Regarding Liluhelper where i cen find this kext?

Thanks for your time  .

Rgds,

Mark

 

Od: vit9696 <notifications@github.com>
Odpowiedź do: vit9696/Lilu <reply@reply.github.com>
Data: czwartek, 8 czerwca 2017 10:36
Do: vit9696/Lilu <Lilu@noreply.github.com>
DW: fixpol <ms@halolamp.pl>, Author <author@noreply.github.com>
Temat: Re: [vit9696/Lilu] lilu.kext kernel panic (#9)

 

Hello, withouts keepsyms=1 in boot-args the panic log is not very helpful. Could you copy the debug versions of the plugins add keepsyms=1 to the boot-args and repeat?

I think you do not have a problem with the Lilu code though, at least it is not even mentioned in the backtrace, so closing the issue.

Also, since you are using Lilu from /L/E, consider building a custom https://github.com/PMheart/LiluFriend plugin.

**Comment by fixpol** [comment] 2017-06-10 15:06
Please check kP with keepsyms=1. Unfortunately I am an expert in mackintosh thus your advise as well as Lilufrienf manual are far to complicated to be done by myself.
[kp 8.06.17 lilu.pdf](https://github.com/vit9696/Lilu/files/1065896/kp.8.06.17.lilu.pdf)

**Comment by vit9696** [comment] 2017-06-10 15:07
Do you see a difference between keepsyms=1 and -keepsyms=1 you added :^)?

**Comment by fixpol** [comment] 2017-06-10 15:09
Rather not

 

 

Od: vit9696 <notifications@github.com>
Odpowiedź do: vit9696/Lilu <reply@reply.github.com>
Data: sobota, 10 czerwca 2017 17:07
Do: vit9696/Lilu <Lilu@noreply.github.com>
DW: Marek Siudym <ms@halolamp.pl>, Author <author@noreply.github.com>
Temat: Re: [vit9696/Lilu] lilu.kext kernel panic (#9)

 

Do you see a difference between keepsyms=1 and -keepsyms=1 you added :^)?

**Comment by fixpol** [comment] 2017-06-10 17:40
Just checked that Lilu.kext is OK. Sorry for bothering you. KP is caused by intelgraphiksfixup.kext  starting from 1.1.1 version. 1.1.0  do not make KP , but also do not fix hd530  intel graphics.

Rgds

 

Od: vit9696 <notifications@github.com>
Odpowiedź do: vit9696/Lilu <reply@reply.github.com>
Data: sobota, 10 czerwca 2017 17:07
Do: vit9696/Lilu <Lilu@noreply.github.com>
DW: Marek Siudym <ms@halolamp.pl>, Author <author@noreply.github.com>
Temat: Re: [vit9696/Lilu] lilu.kext kernel panic (#9)

 

Do you see a difference between keepsyms=1 and -keepsyms=1 you added :^)?

**Comment by vit9696** [comment] 2017-06-10 17:43
Would you stop spamming and start reading already? Stuff like that:

0xffffff81f895b9f0 : 0xffffff800a0ea53c
0xffffff81f895ba70 : 0xffffff800a1ff2dd
0xffffff81f895bc50 : 0xffffff800a09b593
0xffffff81f895bc70 : 0xffffff7f0d10fa80
0xffffff81f895bda0 : 0xffffff800a6408f4
0xffffff81f895be10 : 0xffffff800a64d6b2
0xffffff81f895be60 : 0xffffff800a6b4870
0xffffff81f895be80 : 0xffffff800a696bae
0xffffff81f895bf10 : 0xffffff800a696836
0xffffff81f895bf60 : 0xffffff800a69824e
0xffffff81f895bfb0 : 0xffffff800a0988f7

Is not helpful in any sense. If you want anybody to understand where it panic'ed without doing manual symbolication (that nobody would do), you must add keepsyms=1 to your boot-args. And NOT -keepsyms=1 you added.

**Comment by fixpol** [comment] 2017-06-10 17:58
If I install  separately lilu  and igfx 1.1.0 no panic , but in combo same panic.

 

 

Od: vit9696 <notifications@github.com>
Odpowiedź do: vit9696/Lilu <reply@reply.github.com>
Data: sobota, 10 czerwca 2017 19:43
Do: vit9696/Lilu <Lilu@noreply.github.com>
DW: Marek Siudym <ms@halolamp.pl>, Author <author@noreply.github.com>
Temat: Re: [vit9696/Lilu] lilu.kext kernel panic (#9)

 

Would you stop spamming and start reading already? Stuff like that:

0xffffff81f895b9f0 : 0xffffff800a0ea53c
0xffffff81f895ba70 : 0xffffff800a1ff2dd
0xffffff81f895bc50 : 0xffffff800a09b593
0xffffff81f895bc70 : 0xffffff7f0d10fa80
0xffffff81f895bda0 : 0xffffff800a6408f4
0xffffff81f895be10 : 0xffffff800a64d6b2
0xffffff81f895be60 : 0xffffff800a6b4870
0xffffff81f895be80 : 0xffffff800a696bae
0xffffff81f895bf10 : 0xffffff800a696836
0xffffff81f895bf60 : 0xffffff800a69824e
0xffffff81f895bfb0 : 0xffffff800a0988f7

Is not helpful in any sense. If you want anybody to understand where it panic'ed without doing manual symbolication (that nobody would do), you must add keepsyms=1 to your boot-args. And NOT -keepsyms=1 you added.

**Comment by vandroiy2013** [comment] 2017-06-10 18:04
Lilu & IntelGraphicsFixup should be both LATEST versions. Lilu 1.1.4 & IntelGraphicsFixup 1.1.3

**Comment by fixpol** [comment] 2017-06-10 18:45
So when installed both latest get KP as in attaché keepsyms=1 file.

 

Od: vandroiy2013 <notifications@github.com>
Odpowiedź do: vit9696/Lilu <reply@reply.github.com>
Data: sobota, 10 czerwca 2017 20:04
Do: vit9696/Lilu <Lilu@noreply.github.com>
DW: Marek Siudym <ms@halolamp.pl>, Author <author@noreply.github.com>
Temat: Re: [vit9696/Lilu] lilu.kext kernel panic (#9)

 

Lilu & IntelGraphicsFixup should be both LATEST versions. Lilu 1.1.4 & IntelGraphicsFixup 1.1.3

**Comment by dawiddr** [comment] 2017-06-12 18:33
Hi,
I'm also getting a kernel panic on boot on macOS 10.12.5. I'm using Lilu 1.1.4 & IntelGraphicsFixup 1.1.3. My graphics card is HD530. I inject kexts with Clover.

Here's what I get with`-liludbg` and `keepsyms=1`:
![kernel panic1](https://user-images.githubusercontent.com/5507098/27048874-c382ebce-4fad-11e7-9e65-12fa9168ee83.jpg)
![kernel panic](https://user-images.githubusercontent.com/5507098/27048655-f5f41b24-4fac-11e7-86cf-f3e5e23808a8.jpg)

**Comment by vit9696** [comment] 2017-06-12 18:42
@dawiddr so you cannot boot completely? The panic log is rather interesting, but I don't even see Lilu there, although it should. Does the panic differ across the bots?

**Comment by dawiddr** [comment] 2017-06-12 19:02
@vit9696 Correct, I can't boot at all unless I specify `-liluoff`. But in that case `kextstat` doesn't mention `AppleIntelSKLGraphicsFramebuffer`, so I assume it's not being loaded at all (?). 

The stack trace is always the same.

The output above is for when I disable binary patches for `AppleIntelSKLGraphicsFramebuffer.kext` in Clover, disable Inject Intel and insert Fake ID. Otherwise I also get kernel panic, but Lilu also fails to patch `AppleIntelSKLGraphicsFramebuffer.kext` (it outputs errors about being unable to load MachInfo).

Now that I've written all of this down, I start to think that this could be unrelated to Lilu. Maybe I get  the panic whether `AppleIntelSKLGraphicsFramebuffer` is being loaded, even unpatched.

**Comment by vit9696** [comment] 2017-06-12 19:07
Mixing patches for the same kext in Lilu and clover is not a very good idea. I could imagine all sorts of nastiness to happen.
If Lilu says it is unable to load the MachInfo, then you probably have the file missing on your filesystem or something alike.
I am afraid the issue is indeed unrelated… just there are a lot of things gone wrong, and Lilu is the last one to discover it.

**Comment by dawiddr** [comment] 2017-06-12 19:11
That's possible. Well, I'll be watching this thread in case something related comes up, but in any case thanks for your impressive work!

**Comment by dawiddr** [comment] 2017-06-15 20:31
Interestingly, I have the same problem on 10.12.4. With `-liluoff` I can boot just fine and get graphics acceleration, but without it there's a panic just after Lilu patches kexts. My binary patches for `AppleIntelSKLGraphicsFramebuffer` are disabled and the output from `-liludbg` seems to indicate that patching goes fine.

**Comment by vit9696** [comment] 2017-06-15 20:43
So, you only have IntelGraphicsFixup and Lilu? Have you tried other kexts e.g. Shiki or AppleALC?
If those work fine, I think the issue might be in IntelGraphicsFixup, or more like in the patches it applies, but I can hardly think of anything...

**Comment by dawiddr** [comment] 2017-06-15 21:17
I've just tried Shiki and AppleALC - I can boot just file with them...

**Comment by vit9696** [comment] 2017-06-15 21:21
I think in this case the answer is obvious. Check what is incompatible between IntelGraphicsFixup and your system.

**Comment by dawiddr** [comment] 2017-06-16 17:43
Kernel panic is now gone. I think it was caused by running Lilu together with pre-Lilu version of AppleALC, which I updated yesterday after your comment. Cheers!

**Comment by fixpol** [comment] 2017-06-18 16:10
I found some solution for lilu KP.  When upgraded  APPLEALC . kext to latest  issue no more KP. Unfortunetelly  igfx.kext still have no impact on my hd 530 and must use fake graphic id to reach desktop. Any solution?

Rgds,

Mark

 

Od: vit9696 <notifications@github.com>
Odpowiedź do: vit9696/Lilu <reply@reply.github.com>
Data: czwartek, 15 czerwca 2017 23:21
Do: vit9696/Lilu <Lilu@noreply.github.com>
DW: Marek Siudym <ms@halolamp.pl>, Author <author@noreply.github.com>
Temat: Re: [vit9696/Lilu] lilu.kext kernel panic (#9)

 

I think in this case the answer is obvious. Check what is incompatible between IntelGraphicsFixup and your system.

**Comment by vit9696** [comment] 2017-06-18 17:53
Maybe you have just another ancient kext? I don't know.
